version: "3"

services:
  kameleoon-back-app:
        image: fedorovegor/kameleoon_trial_task
        build:
          dockerfile: Dockerfile
          context: .
        ports: 
          - "8080:8080"
        environment:
          TZ: Europe/Moscow
          H2_NAME: backdb
          H2_USER: sa
          H2_PASSWORD: password