version: "3"

services:
  kameleoon-back-app:
        image: fedorovegor/kameleoon_trial_task
        build:
          dockerfile: Dockerfile
          context: .
        ports: 
          - "8080:8080"